language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
install:
- dotnet restore Linqor
- dotnet restore Linqor.Tests

script:
- dotnet build Linqor
- dotnet build Linqor.Tests
- cd Linqor.Tests && dotnet test