language: csharp
mono: none
dotnet: 1.0.3
dist: trusty
install:
- dotnet restore
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
- dotnet build
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Linqor.Tests/bin/Release/Linqor.Tests.dll